apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: cp-kafka-pdb
  labels:
    tier: middleware
    service: cp-kafka
spec:
  selector:
    matchLabels:
      tier: middleware
      service: cp-kafka
  minAvailable: 2