apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: cp-zookeeper
  labels:
    tier: middleware
    service: cp-zookeeper
spec:
  serviceName: cp-zookeeper
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: middleware
        service: cp-zookeeper
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "service"
                    operator: In
                    values:
                    - cp-zookeeper
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 120
      containers:
      - name: cp-zookeeper
        imagePullPolicy: IfNotPresent
        image: confluentinc/cp-zookeeper:4.1.1
        command:
          - "bash"
          - "-c"
          - "export ZOOKEEPER_SERVER_ID=$((${HOSTNAME##*-}+1)); exec /etc/confluent/docker/run"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: ZOOKEEPER_SERVERS
          value: "cp-zookeeper-0.cp-zookeeper:2888:3888;cp-zookeeper-1.cp-zookeeper:2888:3888;cp-zookeeper-2.cp-zookeeper:2888:3888"
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/zookeeper/data
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ssd
      resources:
        requests:
          storage: 10Gi